### ISSUE TITLE
When I run the app it is stuck 'connecting to bus...'

### ISSUE THREAD

**Issue by chrylarson** [AllJoyn-Cordova/cordova-lighting-alljoyn#3]
I am running OSX. How do I setup a bus (router?) to get the demo app working?

Thanks!

**Comment by stefangordon** [comment]
This post should point you in the right direction, but don't hesitate to come back with additional questions!
http://www.stefangordon.com/options-for-setting-up-an-alljoyn-router/

**Comment by stefangordon** [comment]
Also you might find useful references in these:
http://www.phongcao.net/working-with-alljoyn-lifx-lightbulbs/
http://www.stefangordon.com/lighting-control-sample-for-alljoyn-cordova-plugin/

**Comment by chrylarson** [comment]
Thanks! I ran the AllJoynChat on OSX and iOS. This seemed to be enough to get an Alljoyn router on the network so the Lighting Control demo could connect to the bus.
